env:
  - CGO_ENABLED=1
before:
  hooks:
    # We strongly recommend running tests to catch any regression before release.
    # Even though, this an optional step.
    # TODO: Enable tests once there are proper tests in place
    # - go test ./...
    # As part of the release doc files are included as a separate deliverable for
    # consumption by Packer.io. To include a separate docs.zip uncomment the following command.
    #- make ci-release-docs
    # Check plugin compatibility with required version of the Packer SDK
    # TODO: Enable checking once it no longer errors inside libgit2
    # - make plugin-check
builds:
  # A separated build to run the packer-plugins-check only once for a linux_amd64 binary
  -
    id: plugin-check
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X {{ .ModulePath }}/version.Version={{.Version}} -X {{ .ModulePath }}/version.VersionPrerelease= '
    goos:
      - linux
    goarch:
      - amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
  -
    id: linux-builds
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X {{ .ModulePath }}/version.Version={{.Version}} -X {{ .ModulePath }}/version.VersionPrerelease= '
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      - goos: linux
        goarch: amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
archives:
- format: zip
  files:
    - none*
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - cmd: signore
    args: ["sign", "--dearmor", "--file", "${artifact}", "--out", "${signature}"]
    artifacts: checksum
    signature: ${artifact}.sig
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
  # As part of the release doc files are included as a separate deliverable for consumption by Packer.io.
  # To include a separate docs.zip uncomment the extra_files config and the docs.zip command hook above.
  #extra_files:
  #- glob: ./docs.zip

changelog:
  skip: true
